### ISSUE TITLE
"list index out of range" error 

### ISSUE THREAD

**Issue by neowisard** [innightwolfsleep/llm_telegram_bot#121]
Hi and thank you very much ! 
I added an admin ID and write to the bot directly - I get answers, everything is fine. ChatML preset.
Then I write to the bot directly from another user who is not in the list of admins and telegram_users.txt is empty, then the bot starts responding ("X typing" during generating), but I don't see any response. 
The script gives the error ERROR:root:thread_get_messagelist index out of range('list index out of range',) and continues to work.

Where could I make a mistake?

Or is it necessary to use only group chat for different users ?

**Comment by neowisard** [comment]
if block exeption in thread_get_message :

`ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py:410> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/llm_telegram_bot/main.py", line 361, in thread_get_message
    reply = await self.send_message(text=answer, chat_id=chat_id)
  File "/usr/local/lib/python3.10/dist-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/data/llm_telegram_bot/main.py", line 230, in send_message
    text = await utils.prepare_text(text, user, "to_user")
  File "/data/llm_telegram_bot/source/utils.py", line 67, in prepare_text
    + cfg.translate_html_tag[0]
IndexError: list index out of range
<|im_start|>system`

**Comment by neowisard** [comment]
There some error in file "/llm telegram_bot/source/utils.py", line 67, and i 've been delete  code of function prepare_text , because llm can chat without translate.
